services:
  dashboard:
    container_name: dashboard
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Mount host folders into the container path used by the application
      - ./logs:/ProjectFolder_Dashboard/logs
      - ./data:/ProjectFolder_Dashboard/data
      # External database mounts
      - type: bind
        source: ${MQQC_DB_PATH}
        target: /external_MQQC_database
        read_only: true
      - type: bind
        source: ${MQQC_DB_PATH_2}
        target: /external_MQQC_database2
        read_only: true
      - type: bind
        source: ${METADATA_DB_PATH}
        target: /external_Meta_database
        read_only: true
      # Internal database mounts
      - type: bind
        source: ./data/${MQQC_DB_NAME_I1}
        target: /data/mqqc_database
        read_only: true
      - type: bind
        source: ./data/${MQQC_DB_NAME_I2}
        target: /data/mqqc_database_2
        read_only: true 
      - type: bind
        source: ./data/${META_DB_NAME}
        target: /data/meta_database
        read_only: true
      - type: bind
        source: ./data/${MERGED_DB_NAME}
        target: /data/MergedDuckDB
        read_only: false
    environment:
      # - MQQC_DB_NAME=${MQQC_DB_NAME}
      - MQQC_DB_NAME_I1=${MQQC_DB_NAME_I1}
      - MQQC_DB_NAME_I2=${MQQC_DB_NAME_I2}
      - META_DB_NAME=${META_DB_NAME}
      - MERGED_DB_NAME=${MERGED_DB_NAME}
      

    restart: "no"  # Don't restart, container will be removed when stopped
    # Remove container when it exits
    labels:
      - "podman.remove=true"

   
